import { Tool } from './types';

export const CATEGORIES = [
    '全部',
    '阅读学习',
    '听力训练',
    '教学辅助',
    '写作评估',
    '写作辅助',
    '阅读理解',
    '语法分析',
    '语法学习',
    '词汇学习',
    '翻译训练',
    '文本分析',
    '儿童教育',
    '考试辅导',
    '互动游戏'
];

// 扣子智能体：在需要「站内对话」的工具里加上 cozeBotId，值为扣子平台的 Bot ID（一串数字）
// 例如：cozeBotId: '7498549748861763619'
export const TOOLS: Tool[] = [
    {
        id: 'word-chain-game',
        title: '英文词语接龙',
        description: '既有趣又富有挑战性的词汇游戏。和我一起玩接龙，扩大你的词汇量！',
        icon: 'link', 
        iconBg: 'bg-pink-50',
        iconColor: 'text-pink-500',
        level: '初级',
        levelColor: 'bg-green-100 text-green-700',
        category: '互动游戏',
        categoryColor: 'bg-yellow-100 text-yellow-700',
        rating: 5.0,
        reviewCount: 1,
        tags: ['游戏', '词汇', 'Coze'],
        systemInstruction: "", 
        // cozeBotId removed in favor of direct link as requested
        externalLink: "https://www.coze.cn/store/agent/7498549748861763619?bid=6j39hkve49000"
    },
    {
        id: 'daily-podcast',
        title: '每日英语听力',
        description: '根据您的水平量身定制的简短有趣的故事。',
        icon: 'headphones',
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-500',
        level: '初级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '听力训练',
        categoryColor: 'bg-blue-100 text-blue-600',
        rating: 4.8,
        reviewCount: 124,
        tags: ['听写训练', '故事生成'],
        systemInstruction: "You are an English teacher hosting a daily podcast...",
        // cozeBotId: '你的扣子Bot ID',  // 填写后点击「开始」会在站内弹窗用扣子对话
    },
    {
        id: 'ielts-speaking',
        title: '雅思口语陪练',
        description: '模拟雅思口语面试，提供发音和流利度的AI反馈。',
        icon: 'record_voice_over',
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-500',
        level: '高级',
        levelColor: 'bg-amber-100 text-amber-700',
        category: '考试辅导',
        categoryColor: 'bg-orange-100 text-orange-600',
        rating: 4.9,
        reviewCount: 89,
        tags: ['发音反馈', 'AI模拟'],
        systemInstruction: "You are an IELTS examiner...",
    },
    {
        id: 'grammar-doctor',
        title: '语法分析专家',
        description: '深入分析句子结构，纠正错误并解释原因。',
        icon: 'spellcheck',
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-500',
        level: '全等级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '语法分析',
        categoryColor: 'bg-purple-100 text-purple-600',
        rating: 4.7,
        reviewCount: 215,
        tags: ['成分拆解', '语法纠错'],
        systemInstruction: "You are a syntax expert...",
    },
    {
        id: 'vocab-builder',
        title: '词汇构建助手',
        description: '通过上下文学习扩展您的词汇库。',
        icon: 'school',
        iconBg: 'bg-green-50',
        iconColor: 'text-green-500',
        level: '中级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '词汇学习',
        categoryColor: 'bg-green-100 text-green-600',
        rating: 4.6,
        reviewCount: 56,
        tags: ['记忆卡片', '语境学习'],
        systemInstruction: "You are a vocabulary builder...",
    },
    {
        id: 'news-reader',
        title: '新闻阅读助手',
        description: '阅读适合您词汇水平的时事新闻摘要。',
        icon: 'newspaper',
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-500',
        level: '全等级',
        rating: 4.5,
        reviewCount: 42,
        category: '阅读学习',
        categoryColor: 'bg-indigo-100 text-indigo-600',
        tags: ['时事新闻', '分级阅读'],
        systemInstruction: "You are a news summarizer..."
    },
    {
        id: 'essay-grader',
        title: '作文评分助手',
        description: '对您的写作进行定量和定性分析，提供改进建议。',
        icon: 'history_edu',
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-500',
        level: '高级',
        category: '写作评估',
        categoryColor: 'bg-rose-100 text-rose-600',
        rating: 5.0,
        reviewCount: 18,
        tags: ['作文评分', '改进建议'],
        systemInstruction: "You are an essay grader..."
    },
    {
        id: 'live-translator',
        title: '实时翻译官',
        description: '针对短语和习语的语境感知翻译。',
        icon: 'translate',
        iconBg: 'bg-cyan-50',
        iconColor: 'text-cyan-500',
        level: '全等级',
        rating: 4.8,
        reviewCount: 342,
        category: '翻译训练',
        categoryColor: 'bg-cyan-100 text-cyan-600',
        tags: ['地道表达', '多语言'],
        systemInstruction: "You are a context-aware translator..."
    },
    {
        id: 'roleplay-bot',
        title: '角色扮演冒险',
        description: '在互动游戏格式中练习现实生活场景。',
        icon: 'sports_esports',
        iconBg: 'bg-yellow-50',
        iconColor: 'text-yellow-600',
        level: '中级',
        category: '互动游戏',
        categoryColor: 'bg-yellow-100 text-yellow-700',
        rating: 4.7,
        reviewCount: 67,
        tags: ['场景模拟', '口语对话'],
        systemInstruction: "You are a roleplay partner..."
    },
    {
        id: 'business-email',
        title: '商务写作助理',
        description: '提供专业信函模板和AI辅助写作。',
        icon: 'email',
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-500',
        level: '高级',
        category: '写作辅助',
        categoryColor: 'bg-blue-100 text-blue-600',
        rating: 4.9,
        reviewCount: 103,
        tags: ['邮件模板', '职场英语'],
        systemInstruction: "You are a professional business communication coach..."
    },
    {
        id: 'text-graph-analyzer',
        title: '文本语义图谱分析器',
        description: '提取核心概念与实体关系，生成可视化语义网络图，深入理解课文知识脉络。',
        icon: 'hub',
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-600',
        level: '高级',
        category: '阅读理解',
        categoryColor: 'bg-blue-100 text-blue-600',
        rating: 4.7,
        reviewCount: 21,
        tags: ['可视化图谱', '知识脉络'],
        systemInstruction: "Extract key concepts and entities..."
    }
];