import { Tool } from './types';

export const CATEGORIES = [
    '全部',
    '互动游戏',
    '阅读理解',
    '口语训练',
    '语法学习',
    '听力训练',
    '写作辅助',
    '词汇学习',
];

// 扣子智能体：设置 cozeStoreUrl 实现 iframe 嵌入扣子官方聊天页面
// Vibe Coding 应用：设置 externalLink 实现外部链接跳转
export const TOOLS: Tool[] = [
    // ─── 扣子平台智能体（iframe 嵌入）───────────────────────────
    {
        id: 'word-chain-game',
        title: '英文词语接龙',
        description: '既有趣又富有挑战性的词汇游戏。和专属语伴一起玩接龙，在游戏中扩大你的词汇量！',
        icon: 'link',
        iconBg: 'bg-pink-50',
        iconColor: 'text-pink-500',
        level: '初级',
        levelColor: 'bg-green-100 text-green-700',
        category: '互动游戏',
        categoryColor: 'bg-yellow-100 text-yellow-700',
        rating: 5.0,
        reviewCount: 1,
        tags: ['游戏', '词汇', 'Coze'],
        systemInstruction: '',
        cozeBotId: '7498347619044098060',
        cozeStoreUrl: 'https://www.coze.cn/store/agent/7498549748861763619',
    },
    {
        id: 'critical-reading',
        title: '思辨阅读助手',
        description: '培养批判性阅读能力，引导你深入分析文本观点、论证逻辑与修辞手法，提升学术阅读素养。',
        icon: 'menu_book',
        iconBg: 'bg-indigo-50',
        iconColor: 'text-indigo-500',
        level: '中级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '阅读理解',
        categoryColor: 'bg-indigo-100 text-indigo-600',
        rating: 4.8,
        reviewCount: 36,
        tags: ['批判思维', '文本分析', 'Coze'],
        systemInstruction: '',
        cozeBotId: '7503132500282540072',
        cozeStoreUrl: 'https://www.coze.cn/store/agent/7503187909831311394',
    },
    {
        id: 'cet4-speaking',
        title: '英语四级口语考试陪练',
        description: '模拟大学英语四级口语考试场景，提供实时对话练习与反馈，助你自信应考。',
        icon: 'record_voice_over',
        iconBg: 'bg-orange-50',
        iconColor: 'text-orange-500',
        level: '中级',
        levelColor: 'bg-amber-100 text-amber-700',
        category: '口语训练',
        categoryColor: 'bg-orange-100 text-orange-600',
        rating: 4.9,
        reviewCount: 89,
        tags: ['四级口语', '场景模拟', 'Coze'],
        systemInstruction: '',
        cozeBotId: '7487497199065219108',
        cozeStoreUrl: 'https://www.coze.cn/store/agent/7489270299016511497',
    },
    {
        id: 'grammar-helper',
        title: '语法小帮手',
        description: '遇到语法难题？输入句子即可获得详细的语法分析、错误纠正和规则讲解。',
        icon: 'spellcheck',
        iconBg: 'bg-purple-50',
        iconColor: 'text-purple-500',
        level: '全等级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '语法学习',
        categoryColor: 'bg-purple-100 text-purple-600',
        rating: 4.7,
        reviewCount: 215,
        tags: ['语法纠错', '规则讲解', 'Coze'],
        systemInstruction: '',
        cozeBotId: '7488515481167577100',
        cozeStoreUrl: 'https://www.coze.cn/store/agent/7488554360272732214',
    },
    {
        id: 'complex-sentence',
        title: '英语长难句解析',
        description: '拆解复杂英语句式结构，逐层分析从句、修饰成分与逻辑关系，攻克阅读理解难关。',
        icon: 'account_tree',
        iconBg: 'bg-teal-50',
        iconColor: 'text-teal-500',
        level: '高级',
        levelColor: 'bg-amber-100 text-amber-700',
        category: '阅读理解',
        categoryColor: 'bg-indigo-100 text-indigo-600',
        rating: 4.8,
        reviewCount: 42,
        tags: ['句式拆解', '成分分析', 'Coze'],
        systemInstruction: '',
        cozeBotId: '7478135983478226994',
        cozeStoreUrl: 'https://www.coze.cn/store/agent/7478153626373046335',
    },
    {
        id: 'vocab-buddy',
        title: '词汇活用语伴',
        description: '在真实场景交互中练习词汇，通过自然对话掌握核心词汇的灵活运用和地道表达。',
        icon: 'forum',
        iconBg: 'bg-cyan-50',
        iconColor: 'text-cyan-500',
        level: '全等级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '词汇学习',
        categoryColor: 'bg-green-100 text-green-600',
        rating: 4.8,
        reviewCount: 15,
        tags: ['词汇活用', '情景对话', 'Coze'],
        systemInstruction: '',
        cozeBotId: '7563286786718859303',
        cozeStoreUrl: 'https://www.coze.cn/store/agent/7563286786718859303',
    },

    // ─── Vibe Coding 应用（外部链接跳转）───────────────────
    {
        id: 'dictation-training',
        title: '英语听力训练',
        description: '专业听写训练工具，支持多种难度和场景，通过反复听写提升听力理解能力。',
        icon: 'headphones',
        iconBg: 'bg-blue-50',
        iconColor: 'text-blue-500',
        level: '全等级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '听力训练',
        categoryColor: 'bg-blue-100 text-blue-600',
        rating: 4.8,
        reviewCount: 124,
        tags: ['听写训练', '独立应用'],
        systemInstruction: '',
        externalLink: 'https://dictation.aiforeng.com/',
    },
    {
        id: 'adaptive-writing',
        title: '自适应英语写作',
        description: '根据你的写作水平智能匹配练习难度，提供实时批改建议，循序渐进提升写作能力。',
        icon: 'edit_note',
        iconBg: 'bg-rose-50',
        iconColor: 'text-rose-500',
        level: '全等级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '写作辅助',
        categoryColor: 'bg-rose-100 text-rose-600',
        rating: 4.9,
        reviewCount: 103,
        tags: ['智能批改', '自适应', '独立应用'],
        systemInstruction: '',
        externalLink: 'https://write.aiforeng.com/',
    },
    {
        id: 'vocab-practice',
        title: '词汇练习',
        description: '科学的词汇训练系统，通过多种练习模式巩固记忆，高效扩展你的英语词汇量。',
        icon: 'school',
        iconBg: 'bg-green-50',
        iconColor: 'text-green-500',
        level: '全等级',
        levelColor: 'bg-slate-100 text-slate-600',
        category: '词汇学习',
        categoryColor: 'bg-green-100 text-green-600',
        rating: 4.6,
        reviewCount: 56,
        tags: ['词汇记忆', '练习模式', '独立应用'],
        systemInstruction: '',
        externalLink: 'https://vocabulary.aiforeng.com/',
    },
];